In [2]:
import numpy as np
import matplotlib.pyplot as plt
import os
os.chdir('/home/ch3859/comp-class/comp-lab-class/Week11/')
from psikit import Psikit

In [3]:
# Single point calculation

pk=Psikit(debug=True,threads=1,memory=12)
pk.read_from_smiles("c1ccccc1")
print("SCF Energy: ", pk.energy())
print("HOMO: ", pk.HOMO)
print("LUMO: ", pk.LUMO)
x, y, z, total = pk.dipolemoment
print("SCF Total Dipole Moment: {}".format(total))


  Memory set to  11.176 GiB by Python driver.
  Threads set to 1 by Python driver.
SCF Energy:  -230.71227965267587
HOMO:  -0.32848520376992946
LUMO:  0.14565220772826254
SCF Total Dipole Moment: 0.0


In [4]:
# structure optimization

pk=Psikit(debug=True,threads=1,memory=12)
pk.read_from_smiles("c1ccccc1")
print("Optimized SCF Energy: ", pk.optimize())

Optimizer: Optimization complete!
Optimized SCF Energy:  -230.7135235422025


In [5]:
# calculate RESP charges

pk=Psikit(debug=True,threads=1,memory=12)
pk.read_from_smiles("CC(=O)O")
pk.optimize()
pk.calc_resp_charges()

Optimizer: Optimization complete!


array([-0.26657463,  0.80609514, -0.60321682, -0.66462636,  0.0912277 ,
        0.0912277 ,  0.0912277 ,  0.45463958])

In [6]:
for atom in pk.mol.GetAtoms(): 
    print(atom.GetSymbol(), "ESP:{}\tRESP:{}".format(atom.GetProp("EP"), atom.GetProp("RESP"))) 

C ESP:-0.28288260003115817	RESP:-0.26657462937414306
C ESP:0.80609513593864912	RESP:0.80609513593864912
O ESP:-0.60321681619563994	RESP:-0.60321681619563994
O ESP:-0.66462636173534551	RESP:-0.66462636173534539
H ESP:0.096663686710498853	RESP:0.091227696491493773
H ESP:0.096663686710498853	RESP:0.091227696491493773
H ESP:0.096663686710498853	RESP:0.091227696491493773
H ESP:0.45463958189199799	RESP:0.45463958189199793


In [7]:
# Compute Mulliken charges and Lowdin charges

pk=Psikit(debug=True,threads=1,memory=12)
pk.read_from_smiles("CC(=O)O")
pk.optimize() # or pk.energy()

pk.calc_mulliken_charges()

Optimizer: Optimization complete!


array([-0.41265361,  0.71986584, -0.55390596, -0.58970616,  0.16215402,
        0.1567987 ,  0.15674272,  0.36070445])

In [8]:
pk.calc_lowdin_charges()

array([-0.29413439,  0.33178749, -0.34961791, -0.29234543,  0.12067824,
        0.12156136,  0.12482943,  0.23724121])

In [ ]:
# Rendering Molecular Orbitals

pk=Psikit(debug=True,threads=1,memory=12)
pk.read_from_smiles("c1ccccc1")
pk.optimize(basis_sets="scf/sto-3g")
pk.view_on_pymol() # launch pymol as a RPC server in advance, just type "pymol -R"